<a href="https://colab.research.google.com/github/Abimonalex/DS-LAB/blob/main/DS_lab_03_KNN_iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
from sklearn import datasets
#import the necessary Python libraries, including NumPy, pandas, scikit-learn, and matplotlib for data manipulation, KNN modeling, and visualization.


In [ ]:
iris= datasets.load_iris()
X = iris.data  # Features (sepal length, sepal width, petal length, petal width)
y = iris.target  # Target variable (species: setosa, versicolor, virginica)


In [ ]:
print("Feature Names:", iris.feature_names)

Feature Names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [ ]:
print("Target Names:", iris.target_names)

Target Names: ['setosa' 'versicolor' 'virginica']


In [ ]:
print("Features (data):")
print(iris.data[:5])

Features (data):
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
#Split the Data into Training and Testing Sets

In [ ]:
k = 3
#choosing value for K
knn_classifier = KNeighborsClassifier(n_neighbors=k)
#initialize knn classifier

In [ ]:
knn_classifier.fit(X_train, y_train)
#train knn algo on training data

KNeighborsClassifier(n_neighbors=3)

In [ ]:
y_pred = knn_classifier.predict(X_test)
#Using the trained KNN classifier to make predictions on the test data.


In [ ]:
accuracy = knn_classifier.score(X_test, y_test)
print(f'Accuracy: {accuracy:.2f}')

confusion_mat = confusion_matrix(y_test, y_pred)
print('Confusion Matrix:')
print(confusion_mat)

class_report = classification_report(y_test, y_pred)
print('Classification Report:')
print(class_report)

#model evaluation

Accuracy: 1.00
Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [ ]:
new_data_point = [[5.5, 2.5, 4, 1.5]]

In [ ]:
new_data_prediction = knn_classifier.predict(new_data_point)

In [ ]:
predicted_class_names = [iris.target_names[prediction] for prediction in new_data_prediction]
print("Predicted Class Name:")
print(predicted_class_names)

Predicted Class Name:
['versicolor']
